---
title: "Data Import"
output: github_document
---

This file is for doing data import. 


```{r}
library(tidyverse)
library(readxl) # for excel import
library(haven) # for SAS import
```

## Import two datasets
Import our first dataset

```{r}
litters_df = 
  read_csv(file = "data/FAS_litters.csv",  
           na = c(".", "NA","")
           )

# read_csv is tidyverse updated and better while read.csv is base R

litters_df = janitor::clean_names(litters_df)
```

Import our second dataset
```{r}
pups_df =
  read_csv(file = "data/FAS_pups.csv", 
           skip = 3, # skip 3 rows because the csv has the data codebook on the first few rows
           na = c(".", "NA","") # character vector of strings to interpret as missing values
           ) 
pups_df = janitor::clean_names(pups_df)
```

## Look at the data
```{r}
# litters_df
# pups_df
```

Head or tail
```{r}
head(litters_df, 20)
tail(pups_df, 5)
```

Skimming??

```{r}
skimr::skim(pups_df) # prints an extended summary of what's going on (new function!!)
```

## Oh excel ...

Jenny Bryan made `readxl` to solve our problems. 

```{r}
mlb_df = 
  read_excel("data/mlb11.xlsx")
```

Look at the data!

```{r}
head(mlb_df)
```

Load some LotR data

Import FOTR words.
```{r}
fotr_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```

What about Two Towers?
```{r}
tt_df = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6")

# never commit the ~$ files it's there when the excel or word tab is open it's a temp file that is useless
```

## Import SAS

Read in the PULSE dataset

```{r}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
```



